// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC79gPBJHL4x6t0Sqjb9K3IYDkiuNiLdBA',
    appId: '1:66651268511:web:68b59ef1996a6443e689aa',
    messagingSenderId: '66651268511',
    projectId: 'flutter-ai-b384d',
    authDomain: 'flutter-ai-b384d.firebaseapp.com',
    storageBucket: 'flutter-ai-b384d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNJYPTX2Wsb2WmuMRD_YbeH3QdfTtbxgY',
    appId: '1:66651268511:android:6a3d5257f29c17bee689aa',
    messagingSenderId: '66651268511',
    projectId: 'flutter-ai-b384d',
    storageBucket: 'flutter-ai-b384d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgo5_eO49LAZdPRvFjBFEvwDKSXQlUedE',
    appId: '1:66651268511:ios:bab850fbc11d4034e689aa',
    messagingSenderId: '66651268511',
    projectId: 'flutter-ai-b384d',
    storageBucket: 'flutter-ai-b384d.firebasestorage.app',
    iosBundleId: 'com.example.flutterAiToolkitExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgo5_eO49LAZdPRvFjBFEvwDKSXQlUedE',
    appId: '1:66651268511:ios:bab850fbc11d4034e689aa',
    messagingSenderId: '66651268511',
    projectId: 'flutter-ai-b384d',
    storageBucket: 'flutter-ai-b384d.firebasestorage.app',
    iosBundleId: 'com.example.flutterAiToolkitExample',
  );
}
